name: "Merge base template"
description: "Merge changes from the base 18F guide template for Jekyll"

runs:
  using: "composite"
  steps:
    - run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git remote add -f upstream "https://github.com/18F/isildurs-bane.git"
        git merge --squash --strategy-option=theirs --allow-unrelated-histories upstream/main
        git restore --source=HEAD --staged --worktree -- _guide
        git restore --source=HEAD --staged --worktree -- README.md
        REMOTE_SHA=`git rev-parse upstream/main`
        git commit -m "Merging in 18F/isildurs-bane guide template" -m "18F/isildurs-bane@$REMOTE_SHA"
        git push
      shell: bash
