version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.1
    environment:
      # fix encoding
      - LANG: C.UTF-8
    steps:
      - checkout
      - run: bundle
      - run: bundle exec rake ci_test
